In [7]:
import graphlab
produtos = graphlab.SFrame("amazon_baby.gl/")

In [20]:
produtos

Columns:
	name	str
	review	str
	rating	float
	conta_palavra	dict

Rows: 183531

Data:
+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
|    Planetwise Flannel Wipes   | These flannel wipes are OK... |  3.0   |
|     Planetwise Wipe Pouch     | it came early and was not ... |  5.0   |
| Annas Dream Full Quilt wit... | Very soft and comfortable ... |  5.0   |
| Stop Pacifier Sucking with... | This is a product well wor... |  5.0   |
| Stop Pacifier Sucking with... | All of my kids have cried ... |  5.0   |
| Stop Pacifier Sucking with... | When the Binky Fairy came ... |  5.0   |
| A Tale of Baby's Days with... | Lovely book, it's bound ti... |  4.0   |
| Baby Tracker&reg; - Daily ... | Perfect for new parents. W... |  5.0   |
| Baby Tracker&reg; - Daily ... | A friend of mine pinned th... |  5.0   |
| Baby Tracker&reg; - Daily ... | This has been an easy way ... |  4.0   |
+-------------------------------+-------------------------------+--------+
+-------------------------------+
|         conta_palavra         |
+-------------------------------+
| {'and': 5, '6': 1, 'stink'... |
| {'and': 3, 'love': 1, 'it'... |
| {'and': 2, 'quilt': 1, 'it... |
| {'ingenious': 1, 'and': 3,... |
| {'and': 2, 'parents!!': 1,... |
| {'and': 2, 'this': 2, 'her... |
| {'shop': 1, 'noble': 1, 'i... |
| {'and': 2, 'all': 1, 'righ... |
| {'and': 1, 'help': 1, 'giv... |
| {'journal.': 1, 'nanny': 1... |
+-------------------------------+
[183531 rows x 4 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [21]:
produtos["conta_palavra"] = graphlab.text_analytics.count_words(produtos["review"])

In [22]:
produtos

Columns:
	name	str
	review	str
	rating	float
	conta_palavra	dict

Rows: 183531

Data:
+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
|    Planetwise Flannel Wipes   | These flannel wipes are OK... |  3.0   |
|     Planetwise Wipe Pouch     | it came early and was not ... |  5.0   |
| Annas Dream Full Quilt wit... | Very soft and comfortable ... |  5.0   |
| Stop Pacifier Sucking with... | This is a product well wor... |  5.0   |
| Stop Pacifier Sucking with... | All of my kids have cried ... |  5.0   |
| Stop Pacifier Sucking with... | When the Binky Fairy came ... |  5.0   |
| A Tale of Baby's Days with... | Lovely book, it's bound ti... |  4.0   |
| Baby Tracker&reg; - Daily ... | Perfect for new parents. W... |  5.0   |
| Baby Tracker&reg; - Daily ... | A friend of mine pinned th... |  5.0   |
| Baby Tracker&reg; - Daily ... | This has been an easy way ... |  4.0   |
+-------------------------------+-------------------------------+--------+
+-------------------------------+
|         conta_palavra         |
+-------------------------------+
| {'and': 5, '6': 1, 'stink'... |
| {'and': 3, 'love': 1, 'it'... |
| {'and': 2, 'quilt': 1, 'it... |
| {'ingenious': 1, 'and': 3,... |
| {'and': 2, 'parents!!': 1,... |
| {'and': 2, 'this': 2, 'her... |
| {'shop': 1, 'noble': 1, 'i... |
| {'and': 2, 'all': 1, 'righ... |
| {'and': 1, 'help': 1, 'giv... |
| {'journal.': 1, 'nanny': 1... |
+-------------------------------+
[183531 rows x 4 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [23]:
produtos = produtos[produtos["rating"] != 3]
produtos["sentimento"] = produtos["rating"] >=4

In [24]:
produtos.head()

Columns:
	name	str
	review	str
	rating	float
	conta_palavra	dict
	sentimento	int

Rows: 10

Data:
+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
|     Planetwise Wipe Pouch     | it came early and was not ... |  5.0   |
| Annas Dream Full Quilt wit... | Very soft and comfortable ... |  5.0   |
| Stop Pacifier Sucking with... | This is a product well wor... |  5.0   |
| Stop Pacifier Sucking with... | All of my kids have cried ... |  5.0   |
| Stop Pacifier Sucking with... | When the Binky Fairy came ... |  5.0   |
| A Tale of Baby's Days with... | Lovely book, it's bound ti... |  4.0   |
| Baby Tracker&reg; - Daily ... | Perfect for new parents. W... |  5.0   |
| Baby Tracker&reg; - Daily ... | A friend of mine pinned th... |  5.0   |
| Baby Tracker&reg; - Daily ... | This has been an easy way ... |  4.0   |
| Baby Tracker&reg; - Daily ... | I love this journal and ou... |  4.0   |
+-------------------------------+-------------------------------+--------+
+-------------------------------+------------+
|         conta_palavra         | sentimento |
+-------------------------------+------------+
| {'and': 3, 'love': 1, 'it'... |     1      |
| {'and': 2, 'quilt': 1, 'it... |     1      |
| {'ingenious': 1, 'and': 3,... |     1      |
| {'and': 2, 'parents!!': 1,... |     1      |
| {'and': 2, 'this': 2, 'her... |     1      |
| {'shop': 1, 'noble': 1, 'i... |     1      |
| {'and': 2, 'all': 1, 'righ... |     1      |
| {'and': 1, 'help': 1, 'giv... |     1      |
| {'journal.': 1, 'nanny': 1... |     1      |
| {'all': 1, 'forget': 1, 'j... |     1      |
+-------------------------------+------------+
[10 rows x 5 columns]

In [25]:
produtos["rating"].show(view="Categorical")

Canvas is accessible via web browser at the URL: http://localhost:41887/index.html
Opening Canvas in default web browser.


In [26]:
produtos["rating"].show(view="Categorical")

Canvas is accessible via web browser at the URL: http://localhost:41887/index.html
Opening Canvas in default web browser.


In [12]:
produtos["sentimento"].show(view="Categorical")

Canvas is accessible via web browser at the URL: http://localhost:34833/index.html
Opening Canvas in default web browser.


In [27]:
treino,teste = produtos.random_split(.8, seed=0)
modelo1 = graphlab.logistic_classifier.create(treino,target='sentimento',
features=['conta_palavra'],
validation_set=teste)
modelo2 = graphlab.svm_classifier.create(treino,target='sentimento',
features=['conta_palavra'],
validation_set=teste)

WARNING: The number of feature dimensions in this problem is very large in comparison with the number of examples. Unless an appropriate regularization value is set, this model may not provide accurate predictions for a validation/test set.

Logistic regression:

--------------------------------------------------------

Number of examples          : 133448

Number of classes           : 2

Number of feature columns   : 1

Number of unpacked features : 219217

Number of coefficients    : 219218

Starting L-BFGS

--------------------------------------------------------

+-----------+----------+-----------+--------------+-------------------+---------------------+

| Iteration | Passes   | Step size | Elapsed Time | Training-accuracy | Validation-accuracy |

+-----------+----------+-----------+--------------+-------------------+---------------------+

| 1         | 5        | 0.000002  | 2.333415     | 0.841481          | 0.839989            |

| 2         | 9        | 3.000000  | 3.682453     | 0.947425          | 0.894877            |

| 3         | 10       | 3.000000  | 4.188386     | 0.923768          | 0.866232            |

| 4         | 11       | 3.000000  | 4.688219     | 0.971779          | 0.912743            |

| 5         | 12       | 3.000000  | 5.182475     | 0.975511          | 0.908900            |

| 6         | 13       | 3.000000  | 5.712675     | 0.899991          | 0.825967            |

| 10        | 18       | 1.000000  | 8.169420     | 0.988715          | 0.916256            |

+-----------+----------+-----------+--------------+-------------------+---------------------+

TERMINATED: Iteration limit reached.

This model may not be optimal. To improve it, consider increasing `max_iterations`.

WARNING: The number of feature dimensions in this problem is very large in comparison with the number of examples. Unless an appropriate regularization value is set, this model may not provide accurate predictions for a validation/test set.

SVM:

--------------------------------------------------------

Number of examples          : 133448

Number of classes           : 2

Number of feature columns   : 1

Number of unpacked features : 219217

Number of coefficients    : 219218

Starting L-BFGS

--------------------------------------------------------

+-----------+----------+-----------+--------------+-------------------+---------------------+

| Iteration | Passes   | Step size | Elapsed Time | Training-accuracy | Validation-accuracy |

+-----------+----------+-----------+--------------+-------------------+---------------------+

| 1         | 6        | 0.000001  | 1.428596     | 0.841481          | 0.839989            |

| 2         | 9        | 5.000000  | 2.408733     | 0.952603          | 0.900552            |

| 3         | 10       | 5.000000  | 2.896756     | 0.950970          | 0.889353            |

| 4         | 11       | 5.000000  | 3.393660     | 0.850391          | 0.785761            |

| 5         | 13       | 1.000000  | 4.123983     | 0.974042          | 0.918418            |

| 6         | 14       | 1.000000  | 4.597430     | 0.975459          | 0.918298            |

| 10        | 18       | 1.000000  | 6.489425     | 0.989037          | 0.915566            |

+-----------+----------+-----------+--------------+-------------------+---------------------+

TERMINATED: Iteration limit reached.

This model may not be optimal. To improve it, consider increasing `max_iterations`.

In [28]:
produtos

Columns:
	name	str
	review	str
	rating	float
	conta_palavra	dict
	sentimento	int

Rows: 166752

Data:
+-------------------------------+-------------------------------+--------+
|              name             |             review            | rating |
+-------------------------------+-------------------------------+--------+
|     Planetwise Wipe Pouch     | it came early and was not ... |  5.0   |
| Annas Dream Full Quilt wit... | Very soft and comfortable ... |  5.0   |
| Stop Pacifier Sucking with... | This is a product well wor... |  5.0   |
| Stop Pacifier Sucking with... | All of my kids have cried ... |  5.0   |
| Stop Pacifier Sucking with... | When the Binky Fairy came ... |  5.0   |
| A Tale of Baby's Days with... | Lovely book, it's bound ti... |  4.0   |
| Baby Tracker&reg; - Daily ... | Perfect for new parents. W... |  5.0   |
| Baby Tracker&reg; - Daily ... | A friend of mine pinned th... |  5.0   |
| Baby Tracker&reg; - Daily ... | This has been an easy way ... |  4.0   |
| Baby Tracker&reg; - Daily ... | I love this journal and ou... |  4.0   |
+-------------------------------+-------------------------------+--------+
+-------------------------------+------------+
|         conta_palavra         | sentimento |
+-------------------------------+------------+
| {'and': 3, 'love': 1, 'it'... |     1      |
| {'and': 2, 'quilt': 1, 'it... |     1      |
| {'ingenious': 1, 'and': 3,... |     1      |
| {'and': 2, 'parents!!': 1,... |     1      |
| {'and': 2, 'this': 2, 'her... |     1      |
| {'shop': 1, 'noble': 1, 'i... |     1      |
| {'and': 2, 'all': 1, 'righ... |     1      |
| {'and': 1, 'help': 1, 'giv... |     1      |
| {'journal.': 1, 'nanny': 1... |     1      |
| {'all': 1, 'forget': 1, 'j... |     1      |
+-------------------------------+------------+
[166752 rows x 5 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [16]:
import numpy as np
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsOneClassifier
from sklearn.svm import SVC
from sklearn import cross_validation
from sklearn.metrics import confusion_matrix
import argparse


In [43]:
categories = ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']
dataset = fetch_20newsgroups(subset = 'train', categories = categories, shuffle = True, random_state = 42)


In [32]:
classifier = OneVsOneClassifier(SVC(kernel = 'linear', random_state = 84))

In [33]:
count_vector = CountVectorizer()
tfidf = TfidfTransformer()

In [35]:
def fit_classifier(train_data, train_labels):
    train_counts = count_vector.fit_transform(train_data)
    train_tfidf = tfidf.fit_transform(train_counts)
    classifier.fit(train_tfidf, train_labels)


In [36]:
def predict(test_data):
    test_counts = count_vector.transform(test_data)
    test_tfidf = tfidf.transform(test_counts)
    return classifier.predict(test_tfidf)

In [37]:
print("confusion matrix")

confusion matrix


In [38]:
train_data, test_data, train_labels, test_labels = cross_validation.train_test_split(dataset.data, dataset.target, test_size = 0.1, random_state = 10)

In [39]:
fit_classifier(train_data, train_labels)
predicted = predict(test_data)

In [40]:
print(confusion_matrix(test_labels, predicted, labels = [0, 1, 2, 3]))

[[50  1  1  1]
 [ 0 61  0  0]
 [ 0  3 55  1]
 [ 0  2  0 51]]


In [41]:
print("cross validation")
test_counts = count_vector.fit_transform(dataset.data)
test_tfidf = tfidf.fit_transform(test_counts)

scores = cross_validation.cross_val_score(classifier, test_tfidf, dataset.target, cv = 5)
print(scores)
print("Accuracy: {} +/- {}".format(scores.mean(), scores.std() * 2))

cross validation
[ 0.96460177  0.97345133  0.96238938  0.9579646   0.97327394]
Accuracy: 0.966336204348 +/- 0.0122450509948
